### ISSUE TITLE
Quality control tutorials

### ISSUE THREAD

**Issue by raamana** [LarsonLab/MRI-education-resources#10]
HI There, this is an useful resource. You might consider linking to the videos from the following webinar series
https://crossinvalidation.com/2021/07/19/announcing-quality-conversations-webinar-series-on-niqc-open-science-etc/

**Comment by agentmess** [comment]
Thanks for pointing this out!  I think this is a great research initiative that are highlihgted in this series.
However, right now, I think these topics are out of scope for this project, which is focused on newcomers to MRI, but I will keep it in mind when working with MRI researchers (past newcomer stage) who might benefit
