### ISSUE TITLE
Inclusion of E1 term, in Diagonal Matrix for Matrix form of Bloch Equation Solution

### ISSUE THREAD

**Issue by snawarhussain** [LarsonLab/MRI-education-resources#18]
I was going through the section on the Bloch equations and noticed that the diagonal matrix in the [relaxation](https://larsonlab.github.io/MRI-education-resources/MR%20Physics%20-%20Bloch%20Equation.html#relaxation)
  In the solution, the A matrix is given as  is given as:
 $$diag[exp(-t / T2), exp(-t / T2), 1]$$
 However, based on the mathematical formulation written on the next line for 
$$M_z = M_0 \exp(-t / T_1) + M_0 (1 - \exp(- t / T_1)) $$ 
 shouldn't the diagonal matrix be:
$$diag[exp(-t / T2), exp(-t / T2), exp(-t / T1)]$$

**Comment by agentmess** [comment]
Thank you for catching this!  It is now corrected
