### ISSUE TITLE
Issue on page /Spin Physics.html

### ISSUE THREAD

**Issue by btuan** [LarsonLab/MRI-education-resources#19]
I believe the distributions under the "Fractional Polarization" heading should use $h$ instead of $\bar{h}$.

My rationale is that the Boltzmann distribution goes off of the energy quanta, defined by $E = h\nu$. In the case of spin alignment, the characteristic frequency is $\nu = \bar{\gamma}B_0$. So, I believe the energy term should be $h\bar{\gamma}B_0$ in all of the equations in this section.

**Comment by agentmess** [comment]
Good catch, thanks for reporting!  It is now corrected
